### PR TITLE
Added rotated variants of blocks

### PR DESCRIPTION
**Pull request by a-na-nas**
Random block models will be chosen by the decoration seed

### CODE REVIEW

**Comment by matjojo** [comment]
aww sweet, that's pretty cool. I'll have a look at it on my machine. Thanks

**Comment by matjojo** [comment]
Yeah this makes the conversion a lot smoother and also makes the textures look a lot less fabricated. Since I don't really have anything new planned/in the pipeline I'll just make a release with this change. Is this the name you want me to put in the release post or should I put a different name?

**Comment by a-na-nas** [comment]
If you could please wait a little before next release, I have a few more ideas for improvements

**Comment by matjojo** [comment]
Yeah of course no problem

**Pull request merged**
